-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "sold" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "stock_" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "price" SET DEFAULT 0,
ALTER COLUMN "cost" SET DEFAULT 0,
ALTER COLUMN "stock" SET DEFAULT 0;
